include $(THEOS)/makefiles/common.mk

APPLICATION_NAME = v4hApp
v4hApp_FILES = main.m v4hAppDelegate.m v4hRootViewController.m
v4hApp_FRAMEWORKS = UIKit CoreGraphics Foundation
v4hApp_CFLAGS = -Wno-error -Wno-error=deprecated-declarations -Wno-deprecated-declarations

include $(THEOS_MAKE_PATH)/application.mk