name: Build v4h USB Pro

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Theos environment
        uses: theos/setup-theos-action@v1

      - name: Build Package
        run: |
          # Theos Action đã tự động cài mọi thứ, bạn chỉ việc gõ make
          make package FINALPACKAGE=1
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: v4h-USB-Pro-Deb
          path: packages/*.deb
